[package]
name = "ok-face-mixer-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
env_logger = "0.11.7"
image = "0.25.6"
lazy_static = "1.5.0"
log = "0.4.27"
serde = "1.0.219"
serde_derive = "1.0.219"
