[package]
name = "ok-face-mixer-api"
version = "0.1.0"
edition = "2024"

[dependencies]
ok-face-mixer-core = { path = "../ok-face-mixer-core", features = ["generator"] }

actix-web = "4.10.2"
env_logger = "0.11.7"
log = "0.4.27"
serde = "1.0.219"
serde_derive = "1.0.219"
image = "0.25.6"
